In [1]:
import sympy as sp
B=sp.eye(4)

In [2]:
B[:,0]=2*B[:,0]

In [3]:
B

Matrix([
[2, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [4]:
B[2,:]=0.5*B[2,:]

In [5]:
B

Matrix([
[2, 0,   0, 0],
[0, 1,   0, 0],
[0, 0, 0.5, 0],
[0, 0,   0, 1]])

In [6]:
B[0,:]=B[2,:]+B[0,:]

In [7]:
B

Matrix([
[2, 0, 0.5, 0],
[0, 1,   0, 0],
[0, 0, 0.5, 0],
[0, 0,   0, 1]])

In [8]:
x=B[:,3].copy()
y=B[:,0].copy()

In [9]:
B[:,3]=y
B[:,0]=x

In [10]:
B

Matrix([
[0, 0, 0.5, 2],
[0, 1,   0, 0],
[0, 0, 0.5, 0],
[1, 0,   0, 0]])

In [11]:
L=[0,2,3]
for i in L:
    B[i,:]=B[i,:]-B[1,:]

In [12]:
B

Matrix([
[0, -1, 0.5, 2],
[0,  1,   0, 0],
[0, -1, 0.5, 0],
[1, -1,   0, 0]])

In [13]:
B[:,3]=B[:,2]

In [14]:
B

Matrix([
[0, -1, 0.5, 0.5],
[0,  1,   0,   0],
[0, -1, 0.5, 0.5],
[1, -1,   0,   0]])

In [15]:
B=B[:,1:]

In [16]:
B

Matrix([
[-1, 0.5, 0.5],
[ 1,   0,   0],
[-1, 0.5, 0.5],
[-1,   0,   0]])

In [48]:
from numpy import *
from numpy.linalg import eig

In [49]:
A=matrix([[14,-2],[-8,19]])

In [58]:
A__=A.T@A

In [59]:
A__

matrix([[ 260, -180],
        [-180,  365]])

In [52]:
eig(A__)

(array([125., 500.]),
 matrix([[-0.8,  0.6],
         [-0.6, -0.8]]))

In [62]:
B=matrix([4/5,3/5]).T
B

matrix([[0.8],
        [0.6]])

In [63]:
display(A@B)

matrix([[10.],
        [ 5.]])